---
title: "Milestone 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)

bikeshare <- read_csv("bikeshare.csv")
```

## Drake Deuel

### 2/14/20

I plan to replicate the **Impact of a public transit strike on public bicycle share use: An interrupted time series natural experiment study** a paper by Daniel Fuller et al. published in the June 2019 volume of the Journal of Transport & Health. The paper can be found [here](https://www.sciencedirect.com/science/article/pii/S221414051830553X).

My Github project repository can be found [here](https://github.com/ddeuel/1006-project).

```{r M2, echo=FALSE}

bikeshare %>%
  filter(city == "Philly") %>%
  filter(passholder_type == "Indego30") %>%
  filter(month > 8) %>%
  ggplot(aes(x = start_time, y = number_trips)) +
  geom_line() +
  labs(title = "Philadelphia Bike Share",
       subtitle = "September to January 2016",
       x = "Date",
       y = "Number of Member Trips",
       caption = "Data sourced from David Fuller on Harvard Dataverse")

```